"use client";

import { useState } from "react";
import Link from "next/link";
import { toast } from "sonner";
import { ArrowLeft, BarChart3, Bell, BriefcaseBusiness, Download, ExternalLink, ImageUp, Inbox, LogOut, PackageOpen, Pencil, Pin, Plus, Save, Settings2, ShieldCheck, StickyNote, Trash2, Users } from "lucide-react";
import type { AdminData, AdminNote, ContactLead, ContactLeadStatus, Member, Package, Project, Stat } from "@/lib/types";
import { csvCell } from "@/lib/contact";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Toaster } from "@/components/ui/sonner";

async function submit(form: FormData) {
  const response = await fetch("/api/admin", { method: "POST", body: form });
  const result = await response.json() as { ok?: boolean; error?: string };
  if (!response.ok) throw new Error(result.error || "Could not save changes");
  return result;
}

function useSave() {
  const [saving, setSaving] = useState(false);
  async function run(form: FormData, message: string) { setSaving(true); try { await submit(form); toast.success(message); setTimeout(() => window.location.reload(), 350); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not save"); setSaving(false); } }
  return { saving, run };
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="admin-field"><span>{label}</span>{children}</label>; }

function DeleteAction({ action, id, label }: { action: string; id: string; label: string }) {
  const { saving, run } = useSave();
  return <AlertDialog><AlertDialogTrigger asChild><Button variant="ghost" size="icon" aria-label={`Delete ${label}`}><Trash2 /></Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete {label}?</AlertDialogTitle><AlertDialogDescription>This removes it from the admin panel and public website. This action cannot be undone.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction disabled={saving} variant="destructive" onClick={() => { const f=new FormData(); f.set("action",action); f.set("id",id); void run(f,`${label} deleted`); }}>Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>;
}

function MemberForm({ member }: { member?: Member }) {
  const { saving, run } = useSave();
  return <form className="admin-form" onSubmit={(event) => { event.preventDefault(); const f=new FormData(event.currentTarget); f.set("action","save_member"); void run(f,"Member saved"); }}>
    <input type="hidden" name="id" value={member?.id ?? ""} /><input type="hidden" name="existingPhotoKey" value={member?.photoKey ?? ""} />
    <div className="form-grid"><Field label="Full name"><Input name="name" defaultValue={member?.name} required /></Field><Field label="Role"><Input name="role" defaultValue={member?.role} required /></Field></div>
    <Field label="Short bio"><Textarea name="bio" rows={4} defaultValue={member?.bio} /></Field>
    <div className="upload-field"><ImageUp /><div><strong>Member photo</strong><span>JPG, PNG, WebP or AVIF · max 5 MB</span></div><Input name="photo" type="file" accept="image/jpeg,image/png,image/webp,image/avif" /></div>
    <div className="form-grid"><Field label="Email"><Input name="email" type="email" defaultValue={member?.email} /></Field><Field label="Instagram URL"><Input name="instagram" type="url" defaultValue={member?.instagram} /></Field><Field label="LinkedIn URL"><Input name="linkedin" type="url" defaultValue={member?.linkedin} /></Field><Field label="Display order"><Input name="sortOrder" type="number" defaultValue={member?.sortOrder ?? 0} /></Field></div>
    <label className="check-field"><input name="active" type="checkbox" defaultChecked={member?.active ?? true} /> Show this member publicly</label>
    <Button disabled={saving} type="submit"><Save /> {saving ? "Saving..." : "Save member"}</Button>
  </form>;
}

function PackageForm({ item }: { item?: Package }) {
  const { saving, run } = useSave();
  return <form className="admin-form" onSubmit={(event) => { event.preventDefault(); const f=new FormData(event.currentTarget); f.set("action","save_package"); void run(f,"Package saved"); }}>
    <input type="hidden" name="id" value={item?.id ?? ""} /><div className="form-grid"><Field label="Package name"><Input name="name" defaultValue={item?.name} required /></Field><Field label="Small label"><Input name="label" defaultValue={item?.label} /></Field><Field label="Price (LKR)"><Input name="price" type="number" min="0" defaultValue={item?.price ?? 0} /></Field><Field label="Price note"><Input name="priceNote" defaultValue={item?.priceNote ?? "/ project"} /></Field></div>
    <Field label="Features — one per line"><Textarea name="features" rows={6} defaultValue={item?.features.join("\n")} /></Field>
    <div className="inline-checks"><label className="check-field"><input name="featured" type="checkbox" defaultChecked={item?.featured} /> Highlight package</label><label className="check-field"><input name="active" type="checkbox" defaultChecked={item?.active ?? true} /> Show publicly</label><Field label="Order"><Input name="sortOrder" type="number" defaultValue={item?.sortOrder ?? 0} /></Field></div>
    <Button disabled={saving} type="submit"><Save /> {saving ? "Saving..." : "Save package"}</Button>
  </form>;
}

function ProjectForm({ project }: { project?: Project }) {
  const { saving, run } = useSave();
  return <form className="admin-form" onSubmit={(event) => { event.preventDefault(); const f=new FormData(event.currentTarget); f.set("action","save_project"); void run(f,"Project saved — live statistics updated"); }}>
    <input type="hidden" name="id" value={project?.id ?? ""} /><div className="form-grid"><Field label="Project name"><Input name="title" defaultValue={project?.title} required /></Field><Field label="Client name"><Input name="clientName" defaultValue={project?.clientName} required /></Field><Field label="Status"><select name="status" defaultValue={project?.status ?? "active"}><option value="active">Active</option><option value="completed">Completed</option></select></Field><Field label="Satisfaction %"><Input name="satisfaction" type="number" min="0" max="100" defaultValue={project?.satisfaction ?? ""} /></Field></div>
    <Button disabled={saving} type="submit"><Save /> {saving ? "Saving..." : "Save project"}</Button>
  </form>;
}

const leadStatusLabels: Record<ContactLeadStatus,string> = { new:"New",contacted:"Contacted",qualified:"Qualified",won:"Won",closed:"Closed",spam:"Spam" };

function leadDate(value:string) { const date=new Date(value); return Number.isNaN(date.getTime())?"—":date.toLocaleString("en-LK",{dateStyle:"medium",timeStyle:"short"}); }

function exportLeads(leads:ContactLead[]) {
  const header=["Name","Email","Phone","Subject","Message","Status","Notes","Received"];
  const rows=leads.map(lead=>[lead.name,lead.email,lead.phone,lead.subject,lead.message,leadStatusLabels[lead.status],lead.notes,lead.createdAt]);
  const csv=`\uFEFF${[header,...rows].map(row=>row.map(csvCell).join(",")).join("\r\n")}`;
  const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})); const link=document.createElement("a");
  link.href=url;link.download=`mikras-leads-${new Date().toISOString().slice(0,10)}.csv`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);
}

function LeadForm({ lead }:{ lead:ContactLead }) {
  const {saving,run}=useSave();
  return <form className="admin-form" onSubmit={(event)=>{event.preventDefault();const f=new FormData(event.currentTarget);f.set("action","save_lead");void run(f,"Lead updated");}}>
    <input type="hidden" name="id" value={lead.id}/>
    <div className="lead-summary"><div><small>NAME</small><strong>{lead.name}</strong></div><div><small>RECEIVED</small><strong>{leadDate(lead.createdAt)}</strong></div><div><small>CONTACT</small><a href={`mailto:${lead.email}`}>{lead.email}</a>{lead.phone&&<a href={`tel:${lead.phone.replace(/\s/g,"")}`}>{lead.phone}</a>}</div></div>
    <div className="lead-message"><small>{lead.subject}</small><p>{lead.message}</p></div>
    <Field label="Lead status"><select name="status" defaultValue={lead.status}>{Object.entries(leadStatusLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></Field>
    <Field label="Internal notes"><Textarea name="notes" rows={5} maxLength={2000} defaultValue={lead.notes} placeholder="Add follow-up details, assignment or outcome..."/></Field>
    <Button disabled={saving} type="submit"><Save/>{saving?"Saving...":"Save lead"}</Button>
  </form>;
}

function LeadsPanel({ leads }:{ leads:ContactLead[] }) {
  const [query,setQuery]=useState(""); const [status,setStatus]=useState("all"); const normalized=query.trim().toLowerCase();
  const filtered=leads.filter(lead=>(status==="all"||lead.status===status)&&(!normalized||[lead.name,lead.email,lead.phone,lead.subject,lead.message].some(value=>value.toLowerCase().includes(normalized))));
  const newCount=leads.filter(lead=>lead.status==="new").length; const wonCount=leads.filter(lead=>lead.status==="won").length;
  return <section className="admin-section"><div className="admin-section-head"><div><h2>Contact enquiries</h2><p>Every public contact submission is stored securely here for follow-up.</p></div><Button variant="outline" disabled={!filtered.length} onClick={()=>exportLeads(filtered)}><Download/>Export CSV</Button></div>
    <div className="lead-stat-grid"><article><small>TOTAL LEADS</small><strong>{leads.length}</strong></article><article><small>NEW</small><strong>{newCount}</strong></article><article><small>WON</small><strong>{wonCount}</strong></article></div>
    <div className="admin-card"><div className="lead-controls"><Input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search name, email, phone or subject..." aria-label="Search leads"/><select value={status} onChange={event=>setStatus(event.target.value)} aria-label="Filter leads by status"><option value="all">All statuses</option>{Object.entries(leadStatusLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></div>
      <Table><TableHeader><TableRow><TableHead>Lead</TableHead><TableHead>Subject</TableHead><TableHead>Status</TableHead><TableHead>Received</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{filtered.length?filtered.map(lead=><TableRow key={lead.id}><TableCell><div className="lead-person"><strong>{lead.name}</strong><a href={`mailto:${lead.email}`}>{lead.email}</a>{lead.phone&&<span>{lead.phone}</span>}</div></TableCell><TableCell><div className="lead-subject"><strong>{lead.subject}</strong><span>{lead.message}</span></div></TableCell><TableCell><span className={`status-pill lead-${lead.status}`}>{leadStatusLabels[lead.status]}</span></TableCell><TableCell>{leadDate(lead.createdAt)}</TableCell><TableCell className="text-right"><div className="row-actions"><Dialog><DialogTrigger asChild><Button variant="ghost" size="icon" aria-label={`Open ${lead.name}`}><Pencil/></Button></DialogTrigger><DialogContent className="admin-dialog"><DialogHeader><DialogTitle>{lead.subject}</DialogTitle><DialogDescription>Review the enquiry and update its follow-up status.</DialogDescription></DialogHeader><LeadForm lead={lead}/></DialogContent></Dialog><DeleteAction action="delete_lead" id={lead.id} label={`${lead.name}'s enquiry`}/></div></TableCell></TableRow>):<TableRow><TableCell colSpan={5}><div className="empty-row"><Inbox/>{leads.length?"No leads match this filter.":"No contact enquiries yet."}</div></TableCell></TableRow>}</TableBody></Table>
    </div>
  </section>;
}

function SettingsPanel({ data }: { data: AdminData }) {
  const { saving, run } = useSave(); const s=data.settings;
  return <section className="admin-section"><div className="admin-section-head"><div><h2>Company & contact details</h2><p>These details update the public website contact section and links.</p></div></div><form className="admin-card admin-form" onSubmit={(event)=>{event.preventDefault();const f=new FormData(event.currentTarget);f.set("action","save_settings");void run(f,"Company details updated");}}>
    <div className="form-grid"><Field label="Company name"><Input name="companyName" defaultValue={s.companyName} /></Field><Field label="Admin / contact name"><Input name="adminName" defaultValue={s.adminName} /></Field><Field label="Phone"><Input name="phone" defaultValue={s.phone} /></Field><Field label="WhatsApp"><Input name="whatsapp" defaultValue={s.whatsapp} /></Field><Field label="Email"><Input name="email" type="email" defaultValue={s.email} /></Field><Field label="Address / service area"><Input name="address" defaultValue={s.address} /></Field><Field label="Instagram URL"><Input name="instagram" type="url" defaultValue={s.instagram} /></Field><Field label="LinkedIn URL"><Input name="linkedin" type="url" defaultValue={s.linkedin} /></Field></div>
    <Field label="WhatsApp default message"><Textarea name="whatsappMessage" rows={3} maxLength={500} defaultValue={s.whatsappMessage} /></Field>
    <div className="form-divider"><span>Hero content</span></div><div className="form-grid"><Field label="Hero title"><Input name="heroTitle" defaultValue={s.heroTitle} /></Field><Field label="Orange accent line"><Input name="heroAccent" defaultValue={s.heroAccent} /></Field></div><Field label="Hero description"><Textarea name="heroText" rows={4} defaultValue={s.heroText} /></Field>
    <Button disabled={saving} type="submit"><Save /> {saving?"Saving...":"Save company details"}</Button>
  </form></section>;
}

function MembersPanel({ members }: { members: Member[] }) {
  return <section className="admin-section"><div className="admin-section-head"><div><h2>Company members</h2><p>Add photos and profiles. Public cards move right-to-left and open in an animated popup.</p></div><Dialog><DialogTrigger asChild><Button><Plus /> Add member</Button></DialogTrigger><DialogContent className="admin-dialog"><DialogHeader><DialogTitle>Add team member</DialogTitle><DialogDescription>Create a complete public member profile.</DialogDescription></DialogHeader><MemberForm /></DialogContent></Dialog></div><div className="admin-card"><Table><TableHeader><TableRow><TableHead>Member</TableHead><TableHead>Role</TableHead><TableHead>Status</TableHead><TableHead>Order</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{members.map(member=><TableRow key={member.id}><TableCell><div className="table-person"><span>{member.photoUrl?<img src={member.photoUrl} alt="" />:member.name.slice(0,2).toUpperCase()}</span><strong>{member.name}</strong></div></TableCell><TableCell>{member.role}</TableCell><TableCell><span className={member.active?"status-pill active":"status-pill"}>{member.active?"Public":"Hidden"}</span></TableCell><TableCell>{member.sortOrder}</TableCell><TableCell className="text-right"><div className="row-actions"><Dialog><DialogTrigger asChild><Button variant="ghost" size="icon" aria-label={`Edit ${member.name}`}><Pencil /></Button></DialogTrigger><DialogContent className="admin-dialog"><DialogHeader><DialogTitle>Edit member</DialogTitle><DialogDescription>Update photo, profile and public visibility.</DialogDescription></DialogHeader><MemberForm member={member} /></DialogContent></Dialog><DeleteAction action="delete_member" id={member.id} label={member.name} /></div></TableCell></TableRow>)}</TableBody></Table></div></section>;
}

function PackagesPanel({ packages }: { packages: Package[] }) {
  return <section className="admin-section"><div className="admin-section-head"><div><h2>Investment packages</h2><p>Change package names, prices, features, order and visibility at any time.</p></div><Dialog><DialogTrigger asChild><Button><Plus /> Add package</Button></DialogTrigger><DialogContent className="admin-dialog"><DialogHeader><DialogTitle>Add package</DialogTitle><DialogDescription>Create a new investment option.</DialogDescription></DialogHeader><PackageForm /></DialogContent></Dialog></div><div className="admin-card"><Table><TableHeader><TableRow><TableHead>Package</TableHead><TableHead>Price</TableHead><TableHead>Status</TableHead><TableHead>Style</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{packages.map(item=><TableRow key={item.id}><TableCell><strong>{item.name}</strong></TableCell><TableCell>LKR {item.price.toLocaleString()}</TableCell><TableCell><span className={item.active?"status-pill active":"status-pill"}>{item.active?"Public":"Hidden"}</span></TableCell><TableCell>{item.featured?"Highlighted":"Standard"}</TableCell><TableCell className="text-right"><div className="row-actions"><Dialog><DialogTrigger asChild><Button variant="ghost" size="icon" aria-label={`Edit ${item.name}`}><Pencil /></Button></DialogTrigger><DialogContent className="admin-dialog"><DialogHeader><DialogTitle>Edit package</DialogTitle><DialogDescription>Changes appear on the public pricing section.</DialogDescription></DialogHeader><PackageForm item={item} /></DialogContent></Dialog><DeleteAction action="delete_package" id={item.id} label={item.name} /></div></TableCell></TableRow>)}</TableBody></Table></div></section>;
}

function StatForm({ stat }: { stat: Stat }) { const {saving,run}=useSave(); return <form className="stat-editor" onSubmit={(event)=>{event.preventDefault();const f=new FormData(event.currentTarget);f.set("action","save_stat");void run(f,"Statistic rule saved");}}><input type="hidden" name="id" value={stat.id}/><input type="hidden" name="sortOrder" value={stat.sortOrder}/><div><small>LIVE VALUE</small><strong>{stat.value}{stat.suffix}</strong></div><Field label="Label"><Input name="label" defaultValue={stat.label}/></Field><div className="stat-inputs"><Field label="Manual value"><Input name="manualValue" type="number" min="0" defaultValue={stat.manualValue}/></Field><Field label="Suffix"><Input name="suffix" defaultValue={stat.suffix}/></Field></div><label className="check-field"><input name="autoMode" type="checkbox" defaultChecked={stat.autoMode}/> Calculate from project records</label><Button size="sm" variant="outline" disabled={saving} type="submit"><Save/>Save rule</Button></form> }

function StatsPanel({ stats, projects }: { stats:Stat[];projects:Project[] }) { return <section className="admin-section"><div className="admin-section-head"><div><h2>Live work & statistics</h2><p>Add real projects. Client, completion and satisfaction counters calculate automatically; manual override remains available.</p></div><Dialog><DialogTrigger asChild><Button><Plus/>Add project</Button></DialogTrigger><DialogContent className="admin-dialog"><DialogHeader><DialogTitle>Add real project</DialogTitle><DialogDescription>This record can update the live public counters.</DialogDescription></DialogHeader><ProjectForm/></DialogContent></Dialog></div><div className="stats-edit-grid">{stats.map(stat=><StatForm stat={stat} key={stat.id}/>)}</div><div className="admin-card"><Table><TableHeader><TableRow><TableHead>Project</TableHead><TableHead>Client</TableHead><TableHead>Status</TableHead><TableHead>Satisfaction</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{projects.length?projects.map(project=><TableRow key={project.id}><TableCell><strong>{project.title}</strong></TableCell><TableCell>{project.clientName}</TableCell><TableCell><span className={project.status==="completed"?"status-pill active":"status-pill"}>{project.status}</span></TableCell><TableCell>{project.satisfaction==null?"—":`${project.satisfaction}%`}</TableCell><TableCell className="text-right"><div className="row-actions"><Dialog><DialogTrigger asChild><Button variant="ghost" size="icon"><Pencil/></Button></DialogTrigger><DialogContent className="admin-dialog"><DialogHeader><DialogTitle>Edit project</DialogTitle><DialogDescription>Update status or satisfaction score.</DialogDescription></DialogHeader><ProjectForm project={project}/></DialogContent></Dialog><DeleteAction action="delete_project" id={project.id} label={project.title}/></div></TableCell></TableRow>):<TableRow><TableCell colSpan={5}><div className="empty-row"><BriefcaseBusiness/>No real projects added yet.</div></TableCell></TableRow>}</TableBody></Table></div></section> }

function NoteForm({note}:{note?:AdminNote}){const{saving,run}=useSave();return <form className="admin-form" onSubmit={event=>{event.preventDefault();const f=new FormData(event.currentTarget);f.set("action","save_note");void run(f,"Private note saved");}}><input type="hidden" name="id" value={note?.id??""}/><Field label="Title"><Input name="title" maxLength={120} defaultValue={note?.title} required/></Field><Field label="Private note"><Textarea name="content" rows={8} maxLength={5000} defaultValue={note?.content} placeholder="Tasks, follow-ups, reminders or internal details..."/></Field><label className="check-field"><input name="pinned" type="checkbox" defaultChecked={note?.pinned}/><Pin/>Pin this note</label><Button disabled={saving} type="submit"><Save/>{saving?"Saving...":"Save private note"}</Button></form>}

function NotesPanel({notes}:{notes:AdminNote[]}){return <section className="admin-section"><div className="admin-section-head"><div><h2>Private admin notes</h2><p>Personal reminders stored in the protected admin database and never shown publicly.</p></div><Dialog><DialogTrigger asChild><Button><Plus/>Add note</Button></DialogTrigger><DialogContent className="admin-dialog"><DialogHeader><DialogTitle>New private note</DialogTitle><DialogDescription>Only a signed-in MIKRAS administrator can access it.</DialogDescription></DialogHeader><NoteForm/></DialogContent></Dialog></div><div className="admin-note-grid">{notes.length?notes.map(note=><article className={note.pinned?"admin-note pinned":"admin-note"} key={note.id}>{note.pinned&&<span><Pin/>PINNED</span>}<h3>{note.title}</h3><p>{note.content||"No additional details."}</p><small>Updated {leadDate(note.updatedAt)}</small><div className="row-actions"><Dialog><DialogTrigger asChild><Button variant="ghost" size="icon" aria-label={`Edit ${note.title}`}><Pencil/></Button></DialogTrigger><DialogContent className="admin-dialog"><DialogHeader><DialogTitle>Edit private note</DialogTitle><DialogDescription>Update this internal reminder.</DialogDescription></DialogHeader><NoteForm note={note}/></DialogContent></Dialog><DeleteAction action="delete_note" id={note.id} label={note.title}/></div></article>):<div className="admin-card empty-row"><StickyNote/>No private notes yet.</div>}</div></section>}

function AdminSettingsPanel({data}:{data:AdminData}){const{saving,run}=useSave();const admin=data.admin;return <section className="admin-section"><div className="admin-section-head"><div><h2>Admin & email settings</h2><p>Manage recovery, lead notification delivery and your secure password.</p></div></div><div className="admin-settings-grid"><form className="admin-card admin-form" onSubmit={event=>{event.preventDefault();const f=new FormData(event.currentTarget);f.set("action","save_admin_preferences");void run(f,"Admin settings updated");}}><div className="settings-card-title"><Bell/><div><h3>Email preferences</h3><p className={admin.emailDeliveryConfigured?"config-ok":"config-warning"}>{admin.emailDeliveryConfigured?"Resend delivery is configured.":"Add RESEND_API_KEY and EMAIL_FROM server secrets to activate email."}</p></div></div><Field label="Login email"><Input value={admin.email} disabled/></Field><Field label="Display name"><Input name="displayName" defaultValue={admin.displayName} maxLength={80} required/></Field><Field label="Password recovery email"><Input name="recoveryEmail" type="email" defaultValue={admin.recoveryEmail} required/></Field><Field label="New lead notification email"><Input name="notificationEmail" type="email" defaultValue={admin.notificationEmail} required/></Field><label className="check-field"><input name="notificationsEnabled" type="checkbox" defaultChecked={admin.notificationsEnabled}/>Email me when the public contact form receives a real enquiry</label><Button disabled={saving} type="submit"><Save/>{saving?"Saving...":"Save email settings"}</Button></form><PasswordForm/></div></section>}

function PasswordForm(){const{saving,run}=useSave();return <form className="admin-card admin-form" onSubmit={event=>{event.preventDefault();const f=new FormData(event.currentTarget);f.set("action","change_password");void run(f,"Password changed securely");}}><div className="settings-card-title"><ShieldCheck/><div><h3>Change password</h3><p>Changing it signs out other active admin sessions.</p></div></div><Field label="Current password"><Input name="currentPassword" type="password" autoComplete="current-password" required/></Field><Field label="New password"><Input name="newPassword" type="password" autoComplete="new-password" minLength={12} maxLength={128} required/></Field><Field label="Confirm new password"><Input name="confirmPassword" type="password" autoComplete="new-password" minLength={12} maxLength={128} required/></Field><small className="password-rule">12+ characters with uppercase, lowercase, number and symbol.</small><Button disabled={saving} type="submit"><ShieldCheck/>{saving?"Changing...":"Change password"}</Button></form>}

export function AdminPanel({ data, userName }: { data:AdminData;userName:string }) {
  async function logout(){try{const f=new FormData();f.set("action","logout");const response=await fetch("/api/admin/auth",{method:"POST",body:f});const result=await response.json() as {redirect?:string};window.location.assign(result.redirect||"/admin/login");}catch{toast.error("Could not sign out. Please try again.");}}
  return <main className="admin-shell"><aside className="admin-rail"><div><span className="admin-logo">M</span><strong>MIKRAS</strong><small>CONTROL ROOM</small></div><nav><Link href="/"><ArrowLeft/>Public website</Link><Link href="/" target="_blank"><ExternalLink/>Open in new tab</Link></nav><button className="admin-signout" type="button" onClick={()=>void logout()}><LogOut/>Sign out</button></aside><div className="admin-main"><header className="admin-header"><div><p>MIKRAS ADMIN PANEL</p><h1>Good to see you, {userName}.</h1></div><span>All website controls in one place</span></header><Tabs defaultValue="leads" className="admin-tabs"><TabsList variant="line"><TabsTrigger value="leads"><Inbox/>Leads {data.leads.filter(lead=>lead.status==="new").length>0&&<span className="admin-tab-count">{data.leads.filter(lead=>lead.status==="new").length}</span>}</TabsTrigger><TabsTrigger value="members"><Users/>Members</TabsTrigger><TabsTrigger value="settings"><Settings2/>Company details</TabsTrigger><TabsTrigger value="stats"><BarChart3/>Live stats</TabsTrigger><TabsTrigger value="packages"><PackageOpen/>Packages</TabsTrigger><TabsTrigger value="notes"><StickyNote/>Notes</TabsTrigger><TabsTrigger value="admin-settings"><ShieldCheck/>Admin settings</TabsTrigger></TabsList><TabsContent value="leads"><LeadsPanel leads={data.leads}/></TabsContent><TabsContent value="members"><MembersPanel members={data.members}/></TabsContent><TabsContent value="settings"><SettingsPanel data={data}/></TabsContent><TabsContent value="stats"><StatsPanel stats={data.stats} projects={data.projects}/></TabsContent><TabsContent value="packages"><PackagesPanel packages={data.packages}/></TabsContent><TabsContent value="notes"><NotesPanel notes={data.notes}/></TabsContent><TabsContent value="admin-settings"><AdminSettingsPanel data={data}/></TabsContent></Tabs></div><Toaster richColors position="top-right"/></main>;
}
